language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install . 
# command to run tests
script:
  - py.test
